#!/bin/tcsh

if ($1 == "-R") then
    set RemoteFlag = "-R"
    shift
else
    set RemoteFlag = ""
endif

set Command = "GDV $RemoteFlag -M -L TestFiles.TestsForLambdaPi.$1 -k TestFiles/TestsForLambdaPi/$1 -l -p TestFiles/TestsForLambdaPi/$1/${1}.p TestFiles/TestsForLambdaPi/$1/${2}*---*.s"
echo "Running $Command"
$Command
