#!/bin/tcsh

if ($1 == "--remote") then
    set RemoteFlag = ""
    shift
else
    set RemoteFlag = "-T"
endif

set Basename = `basename $1 .s`
set Dirname = `dirname $1`
set Command = "/home/tptp/ServiceTools/GDVDir/GDV -t 30 -y 1 $RemoteFlag -p $Dirname/$Basename.p $1"

echo "Running $Command"
$Command
